### ISSUE TITLE
AngelScript compile error under MSVC

### ISSUE THREAD

**Issue by SiriusTR** [kevinbentley/Descent3#10]
When building the project under MSVC (VS2022, using CMake/Ninja, x86 debug settings) I see this error under the AngelScript directory:
`scriptstring.cpp(596): error C2440: 'static_cast': cannot convert from 'void (__thiscall std::basic_string<char,std::char_traits<char>,std::allocator<char>>::* )(const unsigned int,const _Elem)' to 'void (__thiscall std::basic_string<char,std::char_traits<char>,std::allocator<char>>::* )(size_t)'`
This appears to be because MSVC's implementation of the STL implements both prototypes of basic_string::resize using a single method with an optional parameter... which I guess works, but it doesn't allow you to static_cast to the single-parameter version.

I notice that currently I can just remove AngelScript from the CMakeLists and then it's all fine, so I suppose it's not really in use yet. But I assume the intention is to eventually move there... would an appropriate solution be to update the version of AngelScript? Looks like this one is from 2009, so maybe a more current version has, erm, workarounds for the MSVC idiosyncrasy :)

**Comment by kevinbentley** [comment]
I think it's just best to remove it for now. I don't know if we'll go the AngelScript direction, we never got very far in integrating it.

**Comment by jcoby** [comment]
@kevinbentley PR added. It doesn't appear to be integrated with any of the other code and should be able to be removed cleanly.

Upgrading to the latest AngelScript (2.36.1) does fix the compile issues but it also requires C++11 if you'd rather go that direction.
