### ISSUE TITLE
Source for d3edit and other tools

### ISSUE THREAD

**Issue by jcotton42** [kevinbentley/Descent3#11]
Would it be possible to include the source for the D3 tooling as well?

**Comment by kevinbentley** [comment]
I vaguely remember that code being released years ago. I think I put it on SourceForge. I'll see what I can dig up. That was a long time ago, before my gmail account existed, so I have to find some old emails.

**Comment by kevinbentley** [comment]
I found version 1.1, source uploaded [here](https://github.com/kevinbentley/D3Edit)

**Comment by bryanperris** [comment]
I think it would make sense today for that tool to be turned into a blender plugin.

**Comment by kevinbentley** [comment]
Closing this, if someone wants to work on bringing the D3Edit code into this project let me know!
