### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by twoscomplement** [kevinbentley/Descent3#32]
Hi there! It's not clear to me what license this code is released under - would you be willing to [add a LICENSE file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to the repository?

Many thanks!

**Comment by chungy** [comment]
It seems that commits prior to 6a7a14159a80c7c7683e75573dc0094ba96ad0c7 were covered under the MIT license. It's unclear why it was deleted (the commit message is only "Delete").

**Comment by killermosi** [comment]
Maybe @kevinbentley  can clarify why this was done and what are the plans for the source code license.

**Comment by JeodC** [comment]
![image](https://github.com/kevinbentley/Descent3/assets/47716344/9998395c-96ce-40c4-9b84-71fe881e7e36)

**Comment by DanielGibson** [comment]
Urghs that sucks

**Comment by mrdaemon** [comment]
Licensing being unclear actually feels like an issue moving forward, it's difficult to contribute to something that may be legally acted upon later.

Moreover it's going to make distribution of anything done with it difficult for the same reason.

**Comment by Laxystem** [comment]
I would recommend MPL  2.0 for this repo. It's a file-based copyleft license - that is, modified files must be released under the MPL, but new files don't - that way, companies can't resell the game, but it's still possible to create mods with a different license.

**Comment by KellyThomas** [comment]
> that way, companies can't resell the game,

No restrictions on commercial use, they just have to offer the their modifications to the MPL code to their consumers.

**Comment by Laxystem** [comment]
That's what I meant - they have to prominently link to the source code.

**Comment by d10sfan** [comment]
That's a shame, hopefully a true open source license is picked, looking forward to the future of this project.

**Comment by Nolram12345** [comment]
I'd love to see a return of the MIT license, or maybe Apache 2 - MPL2 would be also be cool, but the GPL has proven troublesome with mods in some situations with other old games.

**Comment by DanielGibson** [comment]
I just hope it'll get a real open source license, and not some kind of "you can only use this source for Descent3 source ports, and not commercially" deal.

@kevinbentley If you need an argument for a real open source license for whoever holds the rights on Descent3: It would allow them to use this project (or other community source ports) for their official versions on Steam/GOG/whatever.
If the license is liberal enough (like MIT, unlike GPL), it would even allow them to use code from source ports for future releases on consoles, in case anyone ever wants to do that.

**Comment by pombredanne** [comment]
An interesting question is: who is the copyright holder? and who can license or relicense?

This is kinda unclear.

- Per https://en.wikipedia.org/wiki/Outrage_Games ... the successor of Outrage would be THQ?
- Per https://en.wikipedia.org/wiki/THQ THQ went bankrupt in 2012 and some of its assets were sold, possibly to https://en.wikipedia.org/wiki/Embracer_Group / Nordic Games which later became https://en.wikipedia.org/wiki/THQ_Nordic ? 
- Per linkedin @kevinbentley was a Technology Director at Outrage Entertainment https://www.linkedin.com/in/kevinbentley and was involved with Descent3 development
- Per https://www.gamedeveloper.com/business/-i-descent-i-games-yanked-from-gog-store-thanks-to-royalty-dispute there have been some not too distant royalties issues.

**Comment by kevinbentley** [comment]
I'd like to say that there's not a controversy here, just some due diligence. I realize now that I should have waited to release this code, but waiting for details is why it wasn't release for the past 15 years so far. Like @Arcnor said, if you're concerned about it, please don't offer any contributions. The project is new enough that if anyone objects when it is announced, it won't be hard to back out any previous contribution.

I'll repeat what I've said before though, I don't want anyone to begrudge the owners (which is Parallax software for the record) for whatever license they settle on, it is generous for them to release the code under any license, because they didn't have to, and nobody is being coerced to use the code in any form.

So please be patient, forcing a quick or specific outcome is not going to help.

**Comment by pombredanne** [comment]
@kevinbentley re:
> So please be patient, forcing a quick or specific outcome is not going to help.

Thanks! you rock

**Comment by kevinbentley** [comment]
The code has been released under GPL 3.0

**Comment by purpleidea** [comment]
Awesome work, thanks! Good license for a game. John Carmack did the same.
