### ISSUE TITLE
Minimal C++ standard convention

### ISSUE THREAD

**Issue by winterheart** [kevinbentley/Descent3#4]
Would C++14 ok here? Or maybe even C++17? Which standard proposed to use?

**Comment by kevinbentley** [comment]
IMO, C++17 would be reasonable and I can't think of any reason why not to use it. But I'd like to see some others weigh in on this. Post what you think here please!

**Comment by dsommers** [comment]
In the OpenVPN team, we've moved to C++17 ... Our OpenVPN 3 based code builds nicely on all our officially supported Linux distros (Debian, Ubuntu, RHEL8+, Fedora).  The community does builds on even more distros.

For RHEL-8, you would benefit from adding the gcc-toolset-10 (or newer) compiler.  After installing it, it's easy to enable it - just run `scl enable gcc-toolset-10 bash` and that terminal has the environment set up to use that compiler.

I would say C++17 is perfectly sane and reasonable to use these days.

**Comment by Arcnor** [comment]
C++17 is reasonable, and even supported by the current and past generation of consoles (in case that's relevant either now or in the future) so that one has my vote as well.

**Comment by JeodC** [comment]
> C++17 is reasonable, and even supported by the current and past generation of consoles (in case that's relevant either now or in the future) so that one has my vote as well.

Source ports making their way to homebrews like game consoles and even Linux-based retro handhelds and android phones is so common it's practically guaranteed.

**Comment by kevinbentley** [comment]
Ok, let's officially say we support c++17. I'll update the readme soon, or if someone wants to submit a PR, feel free!
