### ISSUE TITLE
Request tp centralise repos under one Descent 3 project

### ISSUE THREAD

**Issue by arandomguysomewhere** [kevinbentley/Descent3#49]
Hi, firstly, thanks for releasing and actively working on this code. Game preservation supported by the original devs is simply the greatest and I hope more studios follow suit. I'm wondering if the 2 Git repositories - D3Edit (https://github.com/kevinbentley/D3Edit) and Descent 3 itself (this one) - could be brought under one Descent 3 project, making the repositories linked and easier to find until a possible future merge. A layout similar to https://github.com/PocketRelay could be helpful, maybe even enabling the setting up of additional repos if needed for external libraries which can then be linked.

**Comment by JeodC** [comment]
A Descent 3 organization might work for this purpose, but that's Kevin's decision to make.

**Comment by JeodC** [comment]
Overseen by #67
