### ISSUE TITLE
Under which license is the Descent 3 source distributed?

### ISSUE THREAD

**Issue by carlsmedstad** [kevinbentley/Descent3#73]
Hi there,

Maybe I'm missing something obvious, but under which license is the Descent 3 source-code distributed? There is no `LICENSE` file in the root of the repository and the `README` does not mention anything regarding licensing. Is it simply source-available, as in not OSS, or is the intention to to make it properly open-source? If so, under which license?

**Comment by Lgt2x** [comment]
See #32
